apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: openidaas
type: Opaque
stringData:
  mysql-root-password: "${MYSQL_ROOT_PASSWORD}"
  mysql-password: "${MYSQL_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: openidaas
type: Opaque
stringData:
  redis-password: "${REDIS_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: nacos-secret
  namespace: openidaas
type: Opaque
stringData:
  nacos-auth-token: "${NACOS_AUTH_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: openidaas
type: Opaque
stringData:
  jwt-signing-key: "${JWT_SIGNING_KEY}"
